### ISSUE TITLE
/cd and /ls not work

### ISSUE THREAD

**Issue by Suburbanno** [DrLafa/Telegram-remote-access-tool#2]
Hey, some commands are not working, for example, the/CD returns
"Unable to find the specified path" in the console, the / is duplicated:

C: \\Users\\Administrador\\Desktop\\Telegram Bot

But it was supposed to be like this:
C: \ Users\Administrador\ Desktop\Telegram Bot
How to fix?

**Comment by Suburbanno** [comment]
Whn using the /ls command

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\telepot\loop.py", line 37, in run_forever
    self._handle(msg)
  File "flashplayer.py", line 128, in bot_handler
    s = '\n'.join(os.listdir(path=pth))
TypeError: listdir() takes no keyword arguments
